In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
master_frame_venture = pd.read_csv("master_df_CountryAnalysis.csv", encoding='ISO-8859-1')

In [3]:
master_frame_venture.head(50)

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0
1,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0
2,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0
3,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0
4,/organization/1-mainstream,1 Mainstream,Apps|Cable|Distribution|Software,acquired,USA,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0
5,/organization/10-minutes-with,10 Minutes With,Education,operating,GBR,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,09-10-2014,4000000.0
6,/organization/1000memories,1000memories,Curated Web,acquired,USA,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,16-02-2011,2520000.0
7,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/13be128d655076a025221d7fddc90d68,venture,14-10-2009,265940.0
8,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/6aeb32ab3fc05db2b606d7a2466e8c09,venture,15-01-2014,2906832.0
9,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/89317984885b44f02e4befb9dc2e588c,venture,01-08-2014,1500000.0
10,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/fd1b3064232ba9b3cfb5653a619e82e8,venture,05-04-2011,642000.0
11,/organization/100health,Redox,Health Care|Health Care Information Technology...,operating,USA,/funding-round/502f558bee350299fd1ae503e5b9a124,venture,20-10-2015,3530000.0
12,/organization/100plus,100Plus,Analytics,acquired,USA,/funding-round/b5facb0d9dea2f0352b5834892c88c53,venture,02-11-2011,500000.0
13,/organization/1010data,1010data,Software,acquired,USA,/funding-round/482fbf992b48f5c47d0080ab7ec0cb54,venture,08-03-2010,35000000.0
14,/organization/10x-genomics,10X Genomics,Biotechnology|Technology,operating,USA,/funding-round/563923487783bdeb5d0b7872f3d6b99a,venture,12-01-2015,55000000.0
15,/organization/10x-technologies,10X Technologies,Biotechnology,operating,USA,/funding-round/39c1441d5098875a925577d0f2ad3904,venture,12-01-2015,550000.0
16,/organization/11i-solutions,11i Solutions,Enterprise Software,closed,USA,/funding-round/e07501ed6997290b1bef59406bc300a1,venture,22-03-2011,1800000.0
17,/organization/128-technology,128 Technology,Service Providers|Technology,operating,USA,/funding-round/fb6216a30cb566ede89e0bee0623a634,venture,16-12-2014,11999347.0
18,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/2a31dd8a0b006b341cde0f7b721008e6,venture,14-01-2011,2400000.0
19,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/31e8a281fe0247f5f13f7be8afe47e01,venture,12-12-2013,2500000.0
20,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/424129ce1235cfab2655ee81305f7c2b,venture,15-10-2013,15000000.0
21,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/6d3f3797371956ece035b8478c1441b2,venture,09-04-2015,5000000.0
22,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/786f61aa9866f4471151285f5c56be36,venture,03-02-2010,5150000.0
23,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/82ace97530965cd2be8f262836b43ff5,venture,27-03-2008,12400000.0
24,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/ab99fc5a53717b1b53fd6aa5687c5fa9,venture,16-12-2010,6000000.0
25,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/b09fa4a4c5c5f5f19305c39c94b7d673,venture,19-10-2010,20000000.0
26,/organization/140-proof,140 Proof,Advertising|Big Data Analytics|Interest Graph,operating,USA,/funding-round/2dc9ff9c590200195228ce2e153a1423,venture,01-07-2009,3000000.0
27,/organization/140-proof,140 Proof,Advertising|Big Data Analytics|Interest Graph,operating,USA,/funding-round/3d40399001b0a2088620030afc533c83,venture,28-04-2011,2500000.0
28,/organization/16-mile-solutions,16 Mile Solutions,Software,operating,USA,/funding-round/3a671cf6f08fe5d0a878f5627134384c,venture,11-06-2009,199957.0
29,/organization/170-systems,170 Systems,Software,acquired,USA,/funding-round/b84bb882ca873f5fb96535671981196d,venture,16-04-2002,14000000.0
30,/organization/17hats,17hats,Internet,operating,USA,/funding-round/56195451074439e1f61fb0165d50eea1,venture,15-10-2015,4000000.0
31,/organization/17zuoye,17zuoye,Education|Language Learning,operating,USA,/funding-round/69690484f51e15bc27ff52bfe472cd96,venture,01-01-2011,5000000.0
32,/organization/17zuoye,17zuoye,Education|Language Learning,operating,USA,/funding-round/8d87f771e938e0f31641bd600abbafca,venture,01-09-2013,10000000.0
33,/organization/17zuoye,17zuoye,Education|Language Learning,operating,USA,/funding-round/8e27c236a535a50c02a17450ed82a980,venture,24-02-2014,20000000.0
34,/organization/17zuoye,17zuoye,Education|Language Learning,operating,USA,/funding-round/c7d697c15073671f014468332f13fc9f,venture,19-02-2015,100000000.0
35,/organization/180solutions,180Solutions,Advertising|Advertising Platforms|Promotional,closed,USA,/funding-round/e55f5f2b9ee65826cc5bf2e1cc2eec9e,venture,05-04-2004,40000000.0
36,/organization/1bog,One Block Off the Grid (1BOG),Clean Technology|Residential Solar,closed,USA,/funding-round/3d2463c9b97f32b3be8747fbd629961f,venture,11-02-2010,5000000.0
37,/organization/1commmedical,1CommMedical,Health Care|Insurance|Medical,operating,USA,/funding-round/0e09b1025dbe9c264f186481ba8fd6ad,venture,27-04-2015,2500000.0
38,/organization/1energy-systems,1Energy Systems,Software,operating,USA,/funding-round/0502de190cb6fd03ba9435767080bcdb,venture,22-04-2013,1450000.0
39,/organization/1life-healthcare,1Life Healthcare,Health and Wellness|Health Care|Services,operating,USA,/funding-round/3711202f1234c8a7db3fd6ffe5dae750,venture,21-03-2013,30000000.0
40,/organization/1spire,1spire,Manufacturing,operating,USA,/funding-round/324f74ddfbeaac9ce82809fd6223ea8d,venture,20-12-2011,30000.0
41,/organization/1stdibs,1stdibs,E-Commerce,operating,USA,/funding-round/292b074d073fdd9c7e9d8f372c3aa5f6,venture,24-01-2014,15000000.0
42,/organization/1stdibs,1stdibs,E-Commerce,operating,USA,/funding-round/d060bf2fd3aabad0ac342d5ef98d1688,venture,03-12-2012,42000000.0
43,/organization/1world-online,1World Online,Analytics|Big Data|Enterprise Software|Market ...,operating,USA,/funding-round/32936e588a134502712877150198a0b3,venture,13-08-2015,2500000.0
44,/organization/1world-online,1World Online,Analytics|Big Data|Enterprise Software|Market ...,operating,USA,/funding-round/4e30bd5c85d8163239a3479ec979647a,venture,01-12-2013,500000.0
45,/organization/1world-online,1World Online,Analytics|Big Data|Enterprise Software|Market ...,operating,USA,/funding-round/a349bfd7a8d48cfc8b9fdb79480dea7f,venture,02-07-2013,1000000.0
46,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology|Health Diagnostics,operating,USA,/funding-round/1df118940a2af3f77ec91a53c2c2ca79,venture,23-09-2015,2037014.0
47,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology|Health Diagnostics,operating,USA,/funding-round/63f491aa5ca433cdd7e7e75b208b2fab,venture,25-09-2012,150000.0
48,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology|Health Diagnostics,operating,USA,/funding-round/e8f0f6679abd451e58a78cdbf26f6acd,venture,30-10-2015,2158413.0
49,/organization/2080-media,2080 Media,News,operating,USA,/funding-round/281939941d4818948129b8349dbf5f14,venture,30-11-2015,8000000.0

In [4]:
master_frame_venture['category_list']

0                                   Media
1                               Analytics
2                               Analytics
3                               Analytics
4        Apps|Cable|Distribution|Software
                       ...
38798                       Biotechnology
38799                       Biotechnology
38800                       Biotechnology
38801                          E-Commerce
38802                       Biotechnology
Name: category_list, Length: 38803, dtype: object

In [5]:
master_frame_venture['category_list'] = master_frame_venture['category_list'].str.split('|').str[0]

In [6]:
master_frame_venture.head(50)

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0
1,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0
2,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0
3,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0
4,/organization/1-mainstream,1 Mainstream,Apps,acquired,USA,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0
5,/organization/10-minutes-with,10 Minutes With,Education,operating,GBR,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,09-10-2014,4000000.0
6,/organization/1000memories,1000memories,Curated Web,acquired,USA,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,16-02-2011,2520000.0
7,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/13be128d655076a025221d7fddc90d68,venture,14-10-2009,265940.0
8,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/6aeb32ab3fc05db2b606d7a2466e8c09,venture,15-01-2014,2906832.0
9,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/89317984885b44f02e4befb9dc2e588c,venture,01-08-2014,1500000.0
10,/organization/1000museums-com,1000museums.com,Curated Web,operating,USA,/funding-round/fd1b3064232ba9b3cfb5653a619e82e8,venture,05-04-2011,642000.0
11,/organization/100health,Redox,Health Care,operating,USA,/funding-round/502f558bee350299fd1ae503e5b9a124,venture,20-10-2015,3530000.0
12,/organization/100plus,100Plus,Analytics,acquired,USA,/funding-round/b5facb0d9dea2f0352b5834892c88c53,venture,02-11-2011,500000.0
13,/organization/1010data,1010data,Software,acquired,USA,/funding-round/482fbf992b48f5c47d0080ab7ec0cb54,venture,08-03-2010,35000000.0
14,/organization/10x-genomics,10X Genomics,Biotechnology,operating,USA,/funding-round/563923487783bdeb5d0b7872f3d6b99a,venture,12-01-2015,55000000.0
15,/organization/10x-technologies,10X Technologies,Biotechnology,operating,USA,/funding-round/39c1441d5098875a925577d0f2ad3904,venture,12-01-2015,550000.0
16,/organization/11i-solutions,11i Solutions,Enterprise Software,closed,USA,/funding-round/e07501ed6997290b1bef59406bc300a1,venture,22-03-2011,1800000.0
17,/organization/128-technology,128 Technology,Service Providers,operating,USA,/funding-round/fb6216a30cb566ede89e0bee0623a634,venture,16-12-2014,11999347.0
18,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/2a31dd8a0b006b341cde0f7b721008e6,venture,14-01-2011,2400000.0
19,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/31e8a281fe0247f5f13f7be8afe47e01,venture,12-12-2013,2500000.0
20,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/424129ce1235cfab2655ee81305f7c2b,venture,15-10-2013,15000000.0
21,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/6d3f3797371956ece035b8478c1441b2,venture,09-04-2015,5000000.0
22,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/786f61aa9866f4471151285f5c56be36,venture,03-02-2010,5150000.0
23,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/82ace97530965cd2be8f262836b43ff5,venture,27-03-2008,12400000.0
24,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/ab99fc5a53717b1b53fd6aa5687c5fa9,venture,16-12-2010,6000000.0
25,/organization/1366-technologies,1366 Technologies,Manufacturing,operating,USA,/funding-round/b09fa4a4c5c5f5f19305c39c94b7d673,venture,19-10-2010,20000000.0
26,/organization/140-proof,140 Proof,Advertising,operating,USA,/funding-round/2dc9ff9c590200195228ce2e153a1423,venture,01-07-2009,3000000.0
27,/organization/140-proof,140 Proof,Advertising,operating,USA,/funding-round/3d40399001b0a2088620030afc533c83,venture,28-04-2011,2500000.0
28,/organization/16-mile-solutions,16 Mile Solutions,Software,operating,USA,/funding-round/3a671cf6f08fe5d0a878f5627134384c,venture,11-06-2009,199957.0
29,/organization/170-systems,170 Systems,Software,acquired,USA,/funding-round/b84bb882ca873f5fb96535671981196d,venture,16-04-2002,14000000.0
30,/organization/17hats,17hats,Internet,operating,USA,/funding-round/56195451074439e1f61fb0165d50eea1,venture,15-10-2015,4000000.0
31,/organization/17zuoye,17zuoye,Education,operating,USA,/funding-round/69690484f51e15bc27ff52bfe472cd96,venture,01-01-2011,5000000.0
32,/organization/17zuoye,17zuoye,Education,operating,USA,/funding-round/8d87f771e938e0f31641bd600abbafca,venture,01-09-2013,10000000.0
33,/organization/17zuoye,17zuoye,Education,operating,USA,/funding-round/8e27c236a535a50c02a17450ed82a980,venture,24-02-2014,20000000.0
34,/organization/17zuoye,17zuoye,Education,operating,USA,/funding-round/c7d697c15073671f014468332f13fc9f,venture,19-02-2015,100000000.0
35,/organization/180solutions,180Solutions,Advertising,closed,USA,/funding-round/e55f5f2b9ee65826cc5bf2e1cc2eec9e,venture,05-04-2004,40000000.0
36,/organization/1bog,One Block Off the Grid (1BOG),Clean Technology,closed,USA,/funding-round/3d2463c9b97f32b3be8747fbd629961f,venture,11-02-2010,5000000.0
37,/organization/1commmedical,1CommMedical,Health Care,operating,USA,/funding-round/0e09b1025dbe9c264f186481ba8fd6ad,venture,27-04-2015,2500000.0
38,/organization/1energy-systems,1Energy Systems,Software,operating,USA,/funding-round/0502de190cb6fd03ba9435767080bcdb,venture,22-04-2013,1450000.0
39,/organization/1life-healthcare,1Life Healthcare,Health and Wellness,operating,USA,/funding-round/3711202f1234c8a7db3fd6ffe5dae750,venture,21-03-2013,30000000.0
40,/organization/1spire,1spire,Manufacturing,operating,USA,/funding-round/324f74ddfbeaac9ce82809fd6223ea8d,venture,20-12-2011,30000.0
41,/organization/1stdibs,1stdibs,E-Commerce,operating,USA,/funding-round/292b074d073fdd9c7e9d8f372c3aa5f6,venture,24-01-2014,15000000.0
42,/organization/1stdibs,1stdibs,E-Commerce,operating,USA,/funding-round/d060bf2fd3aabad0ac342d5ef98d1688,venture,03-12-2012,42000000.0
43,/organization/1world-online,1World Online,Analytics,operating,USA,/funding-round/32936e588a134502712877150198a0b3,venture,13-08-2015,2500000.0
44,/organization/1world-online,1World Online,Analytics,operating,USA,/funding-round/4e30bd5c85d8163239a3479ec979647a,venture,01-12-2013,500000.0
45,/organization/1world-online,1World Online,Analytics,operating,USA,/funding-round/a349bfd7a8d48cfc8b9fdb79480dea7f,venture,02-07-2013,1000000.0
46,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology,operating,USA,/funding-round/1df118940a2af3f77ec91a53c2c2ca79,venture,23-09-2015,2037014.0
47,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology,operating,USA,/funding-round/63f491aa5ca433cdd7e7e75b208b2fab,venture,25-09-2012,150000.0
48,/organization/20-20-gene-systems-inc,20/20 Gene Systems Inc.,Biotechnology,operating,USA,/funding-round/e8f0f6679abd451e58a78cdbf26f6acd,venture,30-10-2015,2158413.0
49,/organization/2080-media,2080 Media,News,operating,USA,/funding-round/281939941d4818948129b8349dbf5f14,venture,30-11-2015,8000000.0

In [7]:
mapping_frame = pd.read_csv("mapping.csv", encoding='ISO-8859-1')

In [8]:
mapping_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 10 columns):
category_list                              687 non-null object
Automotive & Sports                        688 non-null int64
Blanks                                     688 non-null int64
Cleantech / Semiconductors                 688 non-null int64
Entertainment                              688 non-null int64
Health                                     688 non-null int64
Manufacturing                              688 non-null int64
News, Search and Messaging                 688 non-null int64
Others                                     688 non-null int64
Social, Finance, Analytics, Advertising    688 non-null int64
dtypes: int64(9), object(1)
memory usage: 53.9+ KB

In [9]:
mapping_frame.head()

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1

In [10]:
# Dropping rows whose 'category_list' column is NaN.
mapping_frame = mapping_frame.dropna(subset=['category_list'])

In [11]:
# Coverting the mapping column 'category_list' in both df to lowercase.
master_frame_venture['category_list'] = master_frame_venture['category_list'].str.lower()
mapping_frame['category_list'] = mapping_frame['category_list'].str.lower()

In [12]:
mapping_frame.head(50)

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3d,0,0,0,0,0,1,0,0,0
2,3d printing,0,0,0,0,0,1,0,0,0
3,3d technology,0,0,0,0,0,1,0,0,0
4,accounting,0,0,0,0,0,0,0,0,1
5,active lifestyle,0,0,0,0,1,0,0,0,0
6,ad targeting,0,0,0,0,0,0,0,0,1
7,advanced materials,0,0,0,0,0,1,0,0,0
8,adventure travel,1,0,0,0,0,0,0,0,0
9,advertising,0,0,0,0,0,0,0,0,1
10,advertising exchanges,0,0,0,0,0,0,0,0,1
11,advertising networks,0,0,0,0,0,0,0,0,1
12,advertising platforms,0,0,0,0,0,0,0,0,1
13,advice,0,0,0,0,0,0,0,1,0
14,aerospace,1,0,0,0,0,0,0,0,0
15,agriculture,0,0,0,0,0,1,0,0,0
16,air pollution control,0,0,1,0,0,0,0,0,0
17,algorithms,0,0,0,0,0,0,0,1,0
18,all markets,0,0,0,0,0,0,0,1,0
19,all students,0,0,0,0,0,0,0,1,0
20,alter0tive medicine,0,0,0,0,1,0,0,0,0
21,alumni,0,0,0,0,0,0,0,1,0
22,a0lytics,0,0,0,0,0,0,0,0,1
23,android,0,0,0,0,0,0,0,0,1
24,angels,0,0,0,0,0,0,0,1,0
25,animal feed,0,0,0,0,1,0,0,0,0
26,anything capital intensive,0,0,0,0,0,0,0,0,1
27,app discovery,0,0,0,0,0,0,1,0,0
28,app marketing,0,0,0,0,0,0,1,0,0
29,app stores,0,0,0,0,0,0,1,0,0
30,application performance monitoring,0,0,0,0,0,0,1,0,0
31,application platforms,0,0,0,0,0,0,1,0,0
32,apps,0,0,0,0,0,0,1,0,0
33,aquaculture,0,0,1,0,0,0,0,0,0
34,architecture,0,0,0,0,0,1,0,0,0
35,archiving,0,0,0,0,0,0,1,0,0
36,art,0,0,0,1,0,0,0,0,0
37,artificial intelligence,0,0,0,0,0,0,0,0,1
38,artists globally,0,0,0,1,0,0,0,0,0
39,assisitive technology,0,0,0,0,1,0,0,0,0
40,assisted living,0,0,0,0,1,0,0,0,0
41,auctions,0,0,0,0,0,0,0,0,1
42,audio,0,0,0,1,0,0,0,0,0
43,audiobooks,0,0,0,1,0,0,0,0,0
44,augmented reality,0,0,0,0,0,0,0,0,1
45,auto,1,0,0,0,0,0,0,0,0
46,automated kiosk,1,0,0,0,0,0,0,0,0
47,automotive,1,0,0,0,0,0,0,0,0
48,b2b,0,0,0,0,0,0,0,0,1
49,b2b express delivery,0,0,0,0,0,0,0,0,1
50,babies,0,0,0,0,1,0,0,0,0

In [13]:
# Replacing '0' with 'na' under 'category_list'.
mapping_frame['category_list'] = mapping_frame['category_list'].apply(lambda x: x.replace('0', 'na'))
mapping_frame.head(50)

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3d,0,0,0,0,0,1,0,0,0
2,3d printing,0,0,0,0,0,1,0,0,0
3,3d technology,0,0,0,0,0,1,0,0,0
4,accounting,0,0,0,0,0,0,0,0,1
5,active lifestyle,0,0,0,0,1,0,0,0,0
6,ad targeting,0,0,0,0,0,0,0,0,1
7,advanced materials,0,0,0,0,0,1,0,0,0
8,adventure travel,1,0,0,0,0,0,0,0,0
9,advertising,0,0,0,0,0,0,0,0,1
10,advertising exchanges,0,0,0,0,0,0,0,0,1
11,advertising networks,0,0,0,0,0,0,0,0,1
12,advertising platforms,0,0,0,0,0,0,0,0,1
13,advice,0,0,0,0,0,0,0,1,0
14,aerospace,1,0,0,0,0,0,0,0,0
15,agriculture,0,0,0,0,0,1,0,0,0
16,air pollution control,0,0,1,0,0,0,0,0,0
17,algorithms,0,0,0,0,0,0,0,1,0
18,all markets,0,0,0,0,0,0,0,1,0
19,all students,0,0,0,0,0,0,0,1,0
20,alternative medicine,0,0,0,0,1,0,0,0,0
21,alumni,0,0,0,0,0,0,0,1,0
22,analytics,0,0,0,0,0,0,0,0,1
23,android,0,0,0,0,0,0,0,0,1
24,angels,0,0,0,0,0,0,0,1,0
25,animal feed,0,0,0,0,1,0,0,0,0
26,anything capital intensive,0,0,0,0,0,0,0,0,1
27,app discovery,0,0,0,0,0,0,1,0,0
28,app marketing,0,0,0,0,0,0,1,0,0
29,app stores,0,0,0,0,0,0,1,0,0
30,application performance monitoring,0,0,0,0,0,0,1,0,0
31,application platforms,0,0,0,0,0,0,1,0,0
32,apps,0,0,0,0,0,0,1,0,0
33,aquaculture,0,0,1,0,0,0,0,0,0
34,architecture,0,0,0,0,0,1,0,0,0
35,archiving,0,0,0,0,0,0,1,0,0
36,art,0,0,0,1,0,0,0,0,0
37,artificial intelligence,0,0,0,0,0,0,0,0,1
38,artists globally,0,0,0,1,0,0,0,0,0
39,assisitive technology,0,0,0,0,1,0,0,0,0
40,assisted living,0,0,0,0,1,0,0,0,0
41,auctions,0,0,0,0,0,0,0,0,1
42,audio,0,0,0,1,0,0,0,0,0
43,audiobooks,0,0,0,1,0,0,0,0,0
44,augmented reality,0,0,0,0,0,0,0,0,1
45,auto,1,0,0,0,0,0,0,0,0
46,automated kiosk,1,0,0,0,0,0,0,0,0
47,automotive,1,0,0,0,0,0,0,0,0
48,b2b,0,0,0,0,0,0,0,0,1
49,b2b express delivery,0,0,0,0,0,0,0,0,1
50,babies,0,0,0,0,1,0,0,0,0

In [14]:
# 'category_list' items present in mapping_frame, but not in master_frame_venture
mapping_frame.loc[~mapping_frame['category_list'].isin(master_frame_venture['category_list'])]

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
16,air pollution control,0,0,1,0,0,0,0,0,0
33,aquaculture,0,0,1,0,0,0,0,0,0
49,b2b express delivery,0,0,0,0,0,0,0,0,1
64,biomass power generation,0,0,1,0,0,0,0,0,0
69,boating industry,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
669,video streaming,0,0,0,1,0,0,0,0,0
670,virtual workforces,0,0,0,1,0,0,0,0,0
682,weddings,0,0,0,1,0,0,0,0,0
683,wholesale,0,0,0,0,0,0,0,1,0
686,women,0,0,0,0,0,0,0,1,0

In [15]:
# 'category_list' items present in master_frame_venture, but not in mapping_frame
master_frame_venture.loc[~master_frame_venture['category_list'].isin(mapping_frame['category_list'])]

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
7345,/organization/clean-vehicle-solutions,Clean Vehicle Solutions,natural gas uses,operating,USA,/funding-round/7b991c526219c2edff8789942215d93b,venture,26-02-2010,125000.0
8258,/organization/consensus-point,Consensus Point,enterprise 2.0,operating,USA,/funding-round/11ad1d209af6e06e87467f3432aa735f,venture,19-04-2011,788374.0
8259,/organization/consensus-point,Consensus Point,enterprise 2.0,operating,USA,/funding-round/7cdac9335cdc78285e8dcd1932f8729b,venture,18-07-2012,2600000.0
10162,/organization/dolores-speech-products,Dolores Speech Products,adaptive equipment,operating,USA,/funding-round/ba7393d89b2a5ad0c076e2295794c4ce,venture,07-04-2015,250000.0
12375,/organization/fia-formula-e,FIA Formula E,racing,closed,GBR,/funding-round/19a09624fcf806a4a64809462a4e391c,venture,15-05-2014,68569234.0
12630,/organization/five-below,Five Below,specialty retail,ipo,USA,/funding-round/2a50c59492585ea4080fa67de755a442,venture,14-10-2010,194000000.0
12709,/organization/flexport,Flexport,enterprise 2.0,operating,USA,/funding-round/e890e1058ab6be04e9559cd34ee6382c,venture,06-08-2015,20000000.0
14956,/organization/healthtell,HealthTell,biotechnology and semiconductor,operating,USA,/funding-round/8edf7332fface9972541807a248690b3,venture,13-06-2014,9486929.0
17882,/organization/justinmind,Justinmind,rapidly expanding,operating,USA,/funding-round/c6e9adcef86247dccf8418dc3e4b9a0b,venture,17-12-2007,862000.0
23816,/organization/omega-point-research,Omega Point Research,product search,closed,USA,/funding-round/4870743e3fded9317f5611eb2e848667,venture,14-05-2015,3172815.0
24067,/organization/onspring-technologies,Onspring Technologies,enterprise 2.0,operating,USA,/funding-round/41915df9cc7f5d0ddb603e4671a4b9fe,venture,01-01-2015,2000000.0
29949,/organization/sense-labs-inc-,Sense,greentech,operating,USA,/funding-round/1ed09dae5b9feaba2ae7f56dd1b9bfd2,venture,29-12-2014,2499999.0
30210,/organization/shantiniketan-incorporated,ShantiNiketan Inc.,retirement,closed,USA,/funding-round/96f7fa1fdcc380649723c8effc2a1062,venture,01-08-2008,1100000.0
30211,/organization/shantiniketan-incorporated,ShantiNiketan Inc.,retirement,closed,USA,/funding-round/c6baca436fa80360921d89a06a0a0e93,venture,01-05-2011,2000000.0
35906,/organization/velocomp,Velocomp,adaptive equipment,operating,USA,/funding-round/2cdceb89206aad240a78e58329cec171,venture,09-09-2011,1420000.0

In [16]:
# Merging mapping_frame df into master_frame_venture df
master_frame_venture = pd.merge(master_frame_venture, mapping_frame, how='inner', left_on='category_list', right_on='category_list')

In [17]:
master_frame_venture.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38788 entries, 0 to 38787
Data columns (total 18 columns):
permalink                                  38788 non-null object
name                                       38788 non-null object
category_list                              38788 non-null object
status                                     38788 non-null object
country_code                               38788 non-null object
funding_round_permalink                    38788 non-null object
funding_round_type                         38788 non-null object
funded_at                                  38788 non-null object
raised_amount_usd                          38788 non-null float64
Automotive & Sports                        38788 non-null int64
Blanks                                     38788 non-null int64
Cleantech / Semiconductors                 38788 non-null int64
Entertainment                              38788 non-null int64
Health                                     38788 non-null int64
Manufacturing                              38788 non-null int64
News, Search and Messaging                 38788 non-null int64
Others                                     38788 non-null int64
Social, Finance, Analytics, Advertising    38788 non-null int64
dtypes: float64(1), int64(9), object(8)
memory usage: 5.6+ MB

In [18]:
master_frame_venture.head()

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,/organization/-fame,#fame,media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,0,0,0,1,0,0,0,0,0
1,/organization/90min,90min,media,operating,GBR,/funding-round/21a2cbf6f2fb2a1c2a61e04bf930dfe6,venture,06-10-2015,15000000.0,0,0,0,1,0,0,0,0,0
2,/organization/90min,90min,media,operating,GBR,/funding-round/bd626ed022f5c66574b1afe234f3c90d,venture,07-05-2013,5800000.0,0,0,0,1,0,0,0,0,0
3,/organization/90min,90min,media,operating,GBR,/funding-round/fd4b15e8c97ee2ffc0acccdbe1a98810,venture,26-03-2014,18000000.0,0,0,0,1,0,0,0,0,0
4,/organization/all-def-digital,All Def Digital,media,operating,USA,/funding-round/452a2342fe720285c3b92e9bd927d9ba,venture,06-08-2014,5000000.0,0,0,0,1,0,0,0,0,0

#### Now we have a total of 18 columns post merger. However, the newly merged 10 columns are nothing but one's and zero's, all indicating one only value for the given category. It would be convenient to do further analysis if we could shrink down these 10 columns into one column - say 'sector'.

#### We will use pandas 'melt' function to acheive this

In [19]:
# Store the newly added 10 columns into a seperate Series.
value_vars = master_frame_venture.columns[9:18]
print(value_vars)

# Take the remaining columns as seperate Series.
id_vars = master_frame_venture.columns.difference(value_vars)
# id_vars = np.setdiffid(df.columns, value_vars)                 # Alternative ways of doing the same job.
print(id_vars)

Index(['Automotive & Sports', 'Blanks', 'Cleantech / Semiconductors',
       'Entertainment', 'Health', 'Manufacturing',
       'News, Search and Messaging', 'Others',
       'Social, Finance, Analytics, Advertising'],
      dtype='object')
Index(['category_list', 'country_code', 'funded_at', 'funding_round_permalink',
       'funding_round_type', 'name', 'permalink', 'raised_amount_usd',
       'status'],
      dtype='object')

In [20]:
# Calling the 'melt' function
master_frame_venture = pd.melt(master_frame_venture, id_vars=list(id_vars), value_vars=list(value_vars))

In [21]:
master_frame_venture

,category_list,country_code,funded_at,funding_round_permalink,funding_round_type,name,permalink,raised_amount_usd,status,variable,value
0,media,IND,05-01-2015,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,#fame,/organization/-fame,10000000.0,operating,Automotive & Sports,0
1,media,GBR,06-10-2015,/funding-round/21a2cbf6f2fb2a1c2a61e04bf930dfe6,venture,90min,/organization/90min,15000000.0,operating,Automotive & Sports,0
2,media,GBR,07-05-2013,/funding-round/bd626ed022f5c66574b1afe234f3c90d,venture,90min,/organization/90min,5800000.0,operating,Automotive & Sports,0
3,media,GBR,26-03-2014,/funding-round/fd4b15e8c97ee2ffc0acccdbe1a98810,venture,90min,/organization/90min,18000000.0,operating,Automotive & Sports,0
4,media,USA,06-08-2014,/funding-round/452a2342fe720285c3b92e9bd927d9ba,venture,All Def Digital,/organization/all-def-digital,5000000.0,operating,Automotive & Sports,0
...,...,...,...,...,...,...,...,...,...,...,...
349087,tracking,USA,22-07-2013,/funding-round/b1777df10578e852be3afbe3bc325435,venture,Yapta,/organization/yapta,4220000.0,operating,"Social, Finance, Analytics, Advertising",0
349088,tracking,USA,25-06-2009,/funding-round/ed75e1064eb8b50c01c2e0b691ca9f1e,venture,Yapta,/organization/yapta,2000000.0,operating,"Social, Finance, Analytics, Advertising",0
349089,tracking,USA,29-07-2015,/funding-round/fc066baf3121b060b574214612a6c946,venture,Yapta,/organization/yapta,1786563.0,operating,"Social, Finance, Analytics, Advertising",0
349090,gift registries,USA,09-07-2013,/funding-round/d5713b26dbc5e0c65ccc426377449435,venture,Ziftit,/organization/ziftit,4000000.0,closed,"Social, Finance, Analytics, Advertising",0
349091,task management,USA,08-07-2015,/funding-round/f0126dbea5d6075d8d4a1c2d106d9eca,venture,Zonar Systems,/organization/zonarsystems,50000000.0,operating,"Social, Finance, Analytics, Advertising",0

In [22]:
# Deleting 'value' column rows having 0, which is not required.
master_frame_venture.drop(master_frame_venture[master_frame_venture['value'] == 0].index, axis=0, inplace=True)

In [23]:
# Cross checking
len(master_frame_venture[master_frame_venture['value'] == 0])

0

In [24]:
master_frame_venture.shape

(38788, 11)

#### Got back the same row numbers as before post deleting un wanted 'value = 0' rows.

In [40]:
# Now, drop the 'value' column and rename 'variable' column to may be 'sector'.
master_frame_venture.drop(['value'], axis=1, inplace=True)

master_frame_venture.rename(columns={'variable': 'sector'}, inplace=True)

,category_list,country_code,funded_at,funding_round_permalink,funding_round_type,name,permalink,raised_amount_usd,status,sector
25828,drones,USA,05-11-2012,/funding-round/2785595770e91ab8fd4854ef125ec563,venture,3D Robotics,/organization/3d-robotics,5000000.0,operating,Automotive & Sports
25829,drones,USA,23-04-2015,/funding-round/7ca0d4dc119b6d65eebfb352c3544542,venture,3D Robotics,/organization/3d-robotics,14000000.0,operating,Automotive & Sports
25830,drones,USA,12-09-2013,/funding-round/d6221c11246b0a536ee2cadd9fcf54d3,venture,3D Robotics,/organization/3d-robotics,30000000.0,operating,Automotive & Sports
25831,drones,USA,25-02-2015,/funding-round/ff3c1d1ae1c3486d775095b093d99b58,venture,3D Robotics,/organization/3d-robotics,50000000.0,operating,Automotive & Sports
25832,drones,USA,13-10-2015,/funding-round/156e4fbce54aca39a8be9a1a2fa1fb77,venture,Cape Productions,/organization/cape-productions,10000000.0,operating,Automotive & Sports
...,...,...,...,...,...,...,...,...,...,...
349069,social buying,USA,01-01-2006,/funding-round/e4b456b224280682adc488e9a503c40d,venture,ThisNext,/organization/thisnext,2500000.0,operating,"Social, Finance, Analytics, Advertising"
349070,social + mobile + local,USA,18-09-2013,/funding-round/54166cbfbb75fb604c17a94f2205570e,venture,Thredhq,/organization/thredhq,5000000.0,operating,"Social, Finance, Analytics, Advertising"
349071,social + mobile + local,IND,06-11-2014,/funding-round/3538ad48c1b16d95f34ce0900b392807,venture,Vee,/organization/vee,1000000.0,operating,"Social, Finance, Analytics, Advertising"
349074,consumer behavior,USA,04-06-2004,/funding-round/5d5eeb4e64f1eeba0cda3d0cfd122d7d,venture,TrestleTree,/organization/trestletree,4000000.0,acquired,"Social, Finance, Analytics, Advertising"
349075,consumer behavior,USA,03-08-2015,/funding-round/195738852853780cc8f1220ba6fb761d,venture,CleverTap,/organization/wizrocket-technologies,8000000.0,operating,"Social, Finance, Analytics, Advertising"

In [41]:
# Saving the merged master frame for further analysis
master_frame_venture.to_csv("master_df_SectorAnalysis1.csv", sep=',', index=False)